### ISSUE TITLE
Peggle\Peggle-1.04.lua:2348: attempt to index field 'dropdownSkinPeggle' (a nil value) on login.

### ISSUE THREAD

**Issue by tordenflesk** [adamz01h/wow_peggle#17] opened 2019-05-29 20:41 UTC
**Describe the bug**

**Swatter/Bugcatcher Dump**
1x Peggle\Peggle-1.04.lua:2348: attempt to index field 'dropdownSkinPeggle' (a nil value)
Peggle\Peggle-1.04.lua:2348: in function <Peggle\Peggle.lua:2343>
[C]: ?
[C]: in function `ToggleDropDownMenu'
[string "*:OnClick"]:1: in function <[string "*:OnClick"]:1>

Locals:
self = nil
t = nil
t = LFDQueueFrameTypeDropDown {
 0 = <userdata>
 selectedValue = 1671
 Right = LFDQueueFrameTypeDropDownRight {
 }
 Left = LFDQueueFrameTypeDropDownLeft {
 }
 Icon = LFDQueueFrameTypeDropDownIcon {
 }
 initialize = <function> defined @FrameXML\LFDFrame.lua:372
 Button = LFDQueueFrameTypeDropDownButton {
 }
 Text = LFDQueueFrameTypeDropDownText {
 }
 Middle = LFDQueueFrameTypeDropDownMiddle {
 }
 noResize = 1
}
t = nil
t = nil
t = nil
t = nil
t = nil
t = DropDownList1MenuBackdrop {
 0 = <userdata>
}
(*temporary) = nil
(*temporary) = "Peggle\images\windowBackground"
(*temporary) = "windowBackground"
(*temporary) = <userdata>
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'dropdownSkinPeggle' (a nil value)"
o = <table> {
 TimeBreakdown = <function> defined @Peggle\Peggle.lua:675
 TableFind = <function> defined @Peggle\Peggle.lua:681
 TablePack = <function> defined @Peggle\Peggle.lua:719
 SkinDropdown = <function> defined @Peggle\Peggle.lua:2343
 CreateSlider = <function> defined @Peggle\Peggle.lua:2267
 TableRemove = <function> defined @Peggle\Peggle.lua:691
 CreateSlider_OnValueChanged = <function> defined @Peggle\Peggle.lua:2311
 CreateCaption = <function> defined @Peggle\Peggle.lua:2324
 MinuteDifference = <function> defined @Peggle\Peggle.lua:631
 TableInsertOnce = <function> defined @Peggle\Peggle.lua:703
}
e = <table> {
 SOUND_EXTRABALL1 = 8
 currentView = <table> {
 }
 SOUND_SHOT = 5
 curvedBrick = <table> {
 }
 pegRadius = 8.500000
 SOUND_EXTRABALL3 = 10
 ballRadius = 6
 catcherLoopTime = 6
 ping = 3
 onlineList = <table> {
 }
 brickWidth = 28.900000
 brickHeight = 28.900000
 catcherWidth = 138
 SOUND_POWERUP_BLAST = 23
 boardBoundryBottom = 10
 catcherHeight = 27
 SOUND_COIN_SPIN = 6
 oldUsers = <table> {
 }
 SOUND_APPLAUSE = 1
 SOUND_COIN_DENIED = 7
 sectionYSize = 47
 SOUND_SCORECOUNTER = 25
 boardHeight = 464
 polyTable = <table> {
 }
 SOUND_ODETOJOY = 17
 boardWidth = 554
 sparkleFunc = <function> defined @Peggle\Peggle.lua:2115
 windowWidth = 662
 ballHeight = 12
 SOUND_FIREWORKS_START = 14
 outdatedPop = <unnamed> {
 }
 catcherPolygon = <table> {
 }
 temp = <table> {
 }
 SOUND_FIREWORK_POP = 13
 outdatedText = <unnamed> {
 }
 windowHeight = 548
 stats = <table> {
 }
 name = "Ljubica"
 ANI_CIRCLE_ROT = 5
 ANI_LINE_ROTATOR = 4
 boardXYSections = 10
 SOUND_BALL_ADD = 3
 ANI_ROTATOR = 3
 ANI_CIRCLE = 2
 ANI_LINE = 1
 polygonCorners = <table> {
 }
 commands = <table> {
 }
 days = <table> {
 }
 newInfo = <table> {
 }
 versionID = 1.040000
 offlineList = <table> {
 }
 SOUND_BUMPER = 28
 channels = <table> {
 }
 filterText = "No player named '(.+)' is currently playing."
 SOUND_SIGH = 26
 dropInfo = <table> {
 }
 boardBoundryLeft = 10
 ranks = <table> {
 }
 versionString = "1.04"
 talentTex = <table> {
 }
 GetBackdrop = <function> defined @Peggle\Peggle.lua:74
 zoomDistance = 48
 polygon = <table> {
 }
 SOUND_POWERUP_GUIDE = 22
 SOUND_FEVER_HIT = 12
 SOUND_POWERUP = 21
 artPath = "Peggle\images\"
 SOUND_EXTRABALL2 = 9
 sectionXSize = 56
 boardBoundryTop = 462
 SOUND_PEG_POP = 19
 cCount = 0
 SOUND_PEG_SPARK = 20
 brickTex = <table> {
 }
 locale = <table> {
 }
 boardBoundryRight = 552
 SOUND_PEG_HIT = 18
 SOUND_GONG = 16
 SOUND_GAP_BONUS = 15
 factors = <table> {
 }
 SOUND_FEVER = 11
 sounds = <table> {
 }
 SOUND_RAINBOW = 24
 seconds = 60
 sentList = <table> {
 }
 brickRadius = 15.300000
 SOUND_BUCKET_HIT = 4
 SOUND_BUCKET_BALL = 29
 ANI_NONE = 0
 addonPath = "Peggle"
 SOUND_AWARD = 2
 starColors = <table> {
 }
 soundPath = "Peggle\sounds\"
 SOUND_TIMPANI = 27
 pegHeight = 23.800000
 ballWidth = 12
 pegWidth = 23.800000
 addonName = "PEGGLE"
}

**Additional context**

**Comment by Andy1210** [comment] 2019-06-03 12:53
With the latest development version I don''t have any issues. Can you please try that out? https://github.com/adamz01h/wow_peggle/tree/development

**Please note that since it contains breaking changes to the peggle addon save game files you will lose your current progress in peggle.**

**Comment by tordenflesk** [comment] 2019-06-11 18:21
`22x Peggle\Peggle-2.0.lua:2323: attempt to index field 'dropdownSkinPeggle' (a nil value)
Peggle\Peggle-2.0.lua:2323: in function <Peggle\Peggle.lua:2318>
[C]: ?
[C]: in function `ToggleDropDownMenu'
TomTom\TomTom-v80100-1.0.0-beta.lua:676: in function `onclick'
TomTom\TomTom_Waypoints.lua:273: in function <TomTom\TomTom_Waypoints.lua:269>

Locals:
self = 1
t = nil
t = TomTomDropdown {
 0 = <userdata>
 Right = TomTomDropdownRight {
 }
 Left = TomTomDropdownLeft {
 }
 uid = <table> {
 }
 initialize = <function> defined @TomTom\TomTom.lua:596
 Button = TomTomDropdownButton {
 }
 Text = TomTomDropdownText {
 }
 Middle = TomTomDropdownMiddle {
 }
 Icon = TomTomDropdownIcon {
 }
}
t = "cursor"
t = 0
t = 0
t = nil
t = nil
t = DropDownList1MenuBackdrop {
 0 = <userdata>
}
(*temporary) = nil
(*temporary) = "Peggle\images\windowBackground"
(*temporary) = "windowBackground"
(*temporary) = <userdata>
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'dropdownSkinPeggle' (a nil value)"
o = <table> {
 TimeBreakdown = <function> defined @Peggle\Peggle.lua:685
 TableFind = <function> defined @Peggle\Peggle.lua:691
 TablePack = <function> defined @Peggle\Peggle.lua:729
 SkinDropdown = <function> defined @Peggle\Peggle.lua:2318
 CreateSlider = <function> defined @Peggle\Peggle.lua:2242
 TableRemove = <function> defined @Peggle\Peggle.lua:701
 CreateSlider_OnValueChanged = <function> defined @Peggle\Peggle.lua:2286
 CreateCaption = <function> defined @Peggle\Peggle.lua:2299
 MinuteDifference = <function> defined @Peggle\Peggle.lua:641
 TableInsertOnce = <function> defined @Peggle\Peggle.lua:713
}
e = <table> {
 SOUND_EXTRABALL1 = 8
 currentView = <table> {
 }
 SOUND_SHOT = 5
 curvedBrick = <table> {
 }
 pegRadius = 8.500000
 SOUND_EXTRABALL3 = 10
 ballRadius = 6
 catcherLoopTime = 6
 ping = 3
 onlineList = <table> {
 }
 brickWidth = 28.900000
 brickHeight = 28.900000
 catcherWidth = 138
 SOUND_POWERUP_BLAST = 23
 boardBoundryBottom = 10
 catcherHeight = 27
 SOUND_COIN_SPIN = 6
 oldUsers = <table> {
 }
 SOUND_APPLAUSE = 1
 SOUND_COIN_DENIED = 7
 sectionYSize = 47
 SOUND_SCORECOUNTER = 25
 boardHeight = 464
 polyTable = <table> {
 }
 SOUND_ODETOJOY = 17
 boardWidth = 554
 sparkleFunc = <function> defined @Peggle\Peggle.lua:2090
 windowWidth = 662
 ballHeight = 12
 SOUND_FIREWORKS_START = 14
 outdatedPop = <unnamed> {
 }
 catcherPolygon = <table> {
 }
 temp = <table> {
 }
 SOUND_FIREWORK_POP = 13
 outdatedText = <unnamed> {
 }
 windowHeight = 548
 stats = <table> {
 }
 name = "Ljubica"
 ANI_CIRCLE_ROT = 5
 ANI_LINE_ROTATOR = 4
 boardXYSections = 10
 SOUND_BALL_ADD = 3
 ANI_ROTATOR = 3
 ANI_CIRCLE = 2
 ANI_LINE = 1
 polygonCorners = <table> {
 }
 commands = <table> {
 }
 days = <table> {
 }
 newInfo = <table> {
 }
 versionID = 2
 offlineList = <table> {
 }
 SOUND_BUMPER = 28
 channels = <table> {
 }
 filterText = "No player named '(.+)' is currently playing."
 SOUND_SIGH = 26
 dropInfo = <table> {
 }
 boardBoundryLeft = 10
 ranks = <table> {
 }
 versionString = "2.0"
 talentTex = <table> {
 }
 GetBackdrop = <function> defined @Peggle\Peggle.lua:78
 zoomDistance = 48
 polygon = <table> {
 }
 SOUND_POWERUP_GUIDE = 22
 SOUND_FEVER_HIT = 12
 SOUND_POWERUP = 21
 artPath = "Peggle\images\"
 SOUND_EXTRABALL2 = 9
 sectionXSize = 56
 boardBoundryTop = 462
 SOUND_PEG_POP = 19
 cCount = 0
 SOUND_PEG_SPARK = 20
 brickTex = <table> {
 }
 locale = <table> {
 }
 boardBoundryRight = 552
 SOUND_PEG_HIT = 18
 SOUND_GONG = 16
 SOUND_GAP_BONUS = 15
 factors = <table> {
 }
 SOUND_FEVER = 11
 sounds = <table> {
 }
 SOUND_RAINBOW = 24
 seconds = 60
 sentList = <table> {
 }
 brickRadius = 15.300000
 SOUND_BUCKET_HIT = 4
 SOUND_BUCKET_BALL = 29
 ANI_NONE = 0
 addonPath = "Peggle"
 SOUND_AWARD = 2
 starColors = <table> {
 }
 soundPath = "Peggle\sounds\"
 SOUND_TIMPANI = 27
 pegHeight = 23.800000
 ballWidth = 12
 pegWidth = 23.800000
 addonName = "PEGGLE"
}
`

**Comment by Andy1210** [comment] 2019-06-12 11:19
I couldn't reproduce the issue, I don't know when that part of code is running, but in my opinion its not needed, since its some kind of dropdown skin stuff, so I removed it. The pull request is ready.
Until its merged, you can try from here: https://github.com/Andy1210/wow_peggle I hope it will fix your issue. Please let me know.

Edit: its merged, and the development branch also merged to master, so you can just download it from master :)

**Closed as completed** 2019-06-29 12:01 UTC
